#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include "forge.h"
#include "imagine.h"
#include "betray.h"
#include "enough.h"
#include "seduce.h"
#include "deceive.h"
#include "persuade2.h"
