/*
	This file has been automatically generated by the shimmer industries c-ocoa API generator
	Thus, manual changes to this file will be lost if the file is re-generated.
*/

#ifndef C_OCOA_TYPES_HEADER
#define C_OCOA_TYPES_HEADER

#include <stdbool.h>
#include <objc/runtime.h>
#include <objc/message.h>
#include <objc/NSObjCRuntime.h>

typedef void*	nsobject_t;
typedef void*	nsselector_t;
typedef void*	nsclass_t;

// Forward declarations:
struct _CGSize_;
typedef struct _CGSize_ CGSize;
struct ___TISInputSource_;
typedef struct ___TISInputSource_ __TISInputSource;
struct __NSZone_;
typedef struct __NSZone_ _NSZone;
struct _CGColor_;
typedef struct _CGColor_ CGColor;
struct __NSRange_;
typedef struct __NSRange_ _NSRange;
struct _objc_method_description_;
typedef struct _objc_method_description_ objc_method_description;
struct _CGContext_;
typedef struct _CGContext_ CGContext;
struct ___CGEvent_;
typedef struct ___CGEvent_ __CGEvent;
struct _OpaqueCUIRendererRef_;
typedef struct _OpaqueCUIRendererRef_ OpaqueCUIRendererRef;
struct __NSModalSession_;
typedef struct __NSModalSession_ _NSModalSession;
struct __CGLContextObject_;
typedef struct __CGLContextObject_ _CGLContextObject;
struct _CGPoint_;
typedef struct _CGPoint_ CGPoint;
struct _ValueInterpolator_;
typedef struct _ValueInterpolator_ ValueInterpolator;
struct _CGRect_;
typedef struct _CGRect_ CGRect;
struct __CGLPixelFormatObject_;
typedef struct __CGLPixelFormatObject_ _CGLPixelFormatObject;
struct _Object_;
typedef struct _Object_ Object;

//Original struct: {CGSize=dd}
typedef struct _CGSize_
{
	double member0;
	double member1;
} CGSize;

//Original struct: {CGPoint=dd}
typedef struct _CGPoint_
{
	double member0;
	double member1;
} CGPoint;

//Original struct: {CGRect={CGPoint=dd}{CGSize=dd}}
typedef struct _CGRect_
{
	CGPoint member0;
	CGSize member1;
} CGRect;

//Original struct: {CGAffineTransform=dddddd}
typedef struct _CGAffineTransform_
{
	double member0;
	double member1;
	double member2;
	double member3;
	double member4;
	double member5;
} CGAffineTransform;

//Original struct: {_NSRange=QQ}
typedef struct __NSRange_
{
	unsigned long long member0;
	unsigned long long member1;
} _NSRange;

//Original struct: {NSEdgeInsets=dddd}
typedef struct _NSEdgeInsets_
{
	double member0;
	double member1;
	double member2;
	double member3;
} NSEdgeInsets;

#endif
