/*
	This file has been automatically generated by the shimmer industries c-ocoa API generator
	Thus, manual changes to this file will be lost if the file is re-generated.
*/

#ifndef SHIMMER_C_OCOA_NSPASTEBOARD_HEADER
#define SHIMMER_C_OCOA_NSPASTEBOARD_HEADER

typedef void*	nspasteboard_t;
#include "c_ocoa_types.h"

// Signature from Objective-C Runtime: v dealloc @ :
void 				nspasteboard_dealloc( nspasteboard_t object );

// Signature from Objective-C Runtime: @ name @ :
nsobject_t 			nspasteboard_name( nspasteboard_t object );

// Signature from Objective-C Runtime: q changeCount @ :
long long 			nspasteboard_changeCount( nspasteboard_t object );

// Signature from Objective-C Runtime: @ types @ :
nsobject_t 			nspasteboard_types( nspasteboard_t object );

// Signature from Objective-C Runtime: @ availableTypeFromArray: @ : @
nsobject_t 			nspasteboard_availableTypeFromArray( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c attemptOverwrite: @ : @
char 				nspasteboard_attemptOverwrite( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: q declareTypes:owner: @ : @ @
long long 			nspasteboard_declareTypes( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: c setString:forType: @ : @ @
char 				nspasteboard_setString( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ dataForType: @ : @
nsobject_t 			nspasteboard_dataForType( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c setData:forType: @ : @ @
char 				nspasteboard_setData( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ propertyListForType: @ : @
nsobject_t 			nspasteboard_propertyListForType( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ readObjectsForClasses:options: @ : @ @
nsobject_t 			nspasteboard_readObjectsForClasses( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: q clearContents @ :
long long 			nspasteboard_clearContents( nspasteboard_t object );

// Signature from Objective-C Runtime: c writeObjects: @ : @
char 				nspasteboard_writeObjects( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c setPropertyList:forType: @ : @ @
char 				nspasteboard_setPropertyList( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: q addTypes:owner: @ : @ @
long long 			nspasteboard_addTypes( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ pasteboardItems @ :
nsobject_t 			nspasteboard_pasteboardItems( nspasteboard_t object );

// Signature from Objective-C Runtime: @ stringForType: @ : @
nsobject_t 			nspasteboard_stringForType( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: q prepareForNewContentsWithOptions: @ : Q
long long 			nspasteboard_prepareForNewContentsWithOptions( nspasteboard_t object, unsigned long long arg0 );

// Signature from Objective-C Runtime: Q indexOfPasteboardItem: @ : @
unsigned long long 	nspasteboard_indexOfPasteboardItem( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c canReadItemWithDataConformingToTypes: @ : @
char 				nspasteboard_canReadItemWithDataConformingToTypes( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c canReadObjectForClasses:options: @ : @ @
char 				nspasteboard_canReadObjectForClasses( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: c setDataProvider:forTypes: @ : @ @
char 				nspasteboard_setDataProvider( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: c writeFileContents: @ : @
char 				nspasteboard_writeFileContents( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c writeFileWrapper: @ : @
char 				nspasteboard_writeFileWrapper( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ readFileContentsType:toFile: @ : @ @
nsobject_t 			nspasteboard_readFileContentsType( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ readFileWrapper @ :
nsobject_t 			nspasteboard_readFileWrapper( nspasteboard_t object );

// Signature from Objective-C Runtime: @ accessibilityOverriddenAttributes @ :
nsobject_t 			nspasteboard_accessibilityOverriddenAttributes( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilityReplaceRange:withText: @ : {_NSRange=QQ} @
char 				nspasteboard_accessibilityReplaceRange( nspasteboard_t object, _NSRange arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: d accessibilityVisibleArea @ :
double 				nspasteboard_accessibilityVisibleArea( nspasteboard_t object );

// Signature from Objective-C Runtime: Q accessibilityArrayAttributeCount: @ : @
unsigned long long 	nspasteboard_accessibilityArrayAttributeCount( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: Q accessibilityIndexOfChild: @ : @
unsigned long long 	nspasteboard_accessibilityIndexOfChild( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ accessibilityArrayAttributeValues:index:maxCount: @ : @ Q Q
nsobject_t 			nspasteboard_accessibilityArrayAttributeValues( nspasteboard_t object, nsobject_t arg0, unsigned long long arg1, unsigned long long arg2 );

// Signature from Objective-C Runtime: @ accessibilityParameterizedAttributeNames @ :
nsobject_t 			nspasteboard_accessibilityParameterizedAttributeNames( nspasteboard_t object );

// Signature from Objective-C Runtime: @ accessibilityAttributeValue:forParameter: @ : @ @
nsobject_t 			nspasteboard_accessibilityAttributeValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ accessibilityIndexForChildUIElementAttributeForParameter: @ : @
nsobject_t 			nspasteboard_accessibilityIndexForChildUIElementAttributeForParameter( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ accessibilityAttributedValueForStringAttributeAttributeForParameter: @ : @
nsobject_t 			nspasteboard_accessibilityAttributedValueForStringAttributeAttributeForParameter( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ accessibilityTemporaryChildren @ :
nsobject_t 			nspasteboard_accessibilityTemporaryChildren( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilityPerformShowMenuOfChild: @ : @
char 				nspasteboard_accessibilityPerformShowMenuOfChild( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: i accessibilityPresenterProcessIdentifier @ :
int 				nspasteboard_accessibilityPresenterProcessIdentifier( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilityShouldUseUniqueId @ :
char 				nspasteboard_accessibilityShouldUseUniqueId( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilitySupportsNotifications @ :
char 				nspasteboard_accessibilitySupportsNotifications( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilityShouldSendNotification: @ : @
char 				nspasteboard_accessibilityShouldSendNotification( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c accessibilitySupportsOverriddenAttributes @ :
char 				nspasteboard_accessibilitySupportsOverriddenAttributes( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilityAllowsOverriddenAttributesWhenIgnored @ :
char 				nspasteboard_accessibilityAllowsOverriddenAttributesWhenIgnored( nspasteboard_t object );

// Signature from Objective-C Runtime: c accessibilitySetOverrideValue:forAttribute: @ : @ @
char 				nspasteboard_accessibilitySetOverrideValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v accessibilityEncodeOverriddenAttributes: @ : @
void 				nspasteboard_accessibilityEncodeOverriddenAttributes( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v accessibilityDecodeOverriddenAttributes: @ : @
void 				nspasteboard_accessibilityDecodeOverriddenAttributes( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c accessibilitySupportsCustomElementData @ :
char 				nspasteboard_accessibilitySupportsCustomElementData( nspasteboard_t object );

// Signature from Objective-C Runtime: v bind:toObject:withKeyPath:options: @ : @ @ @ @
void 				nspasteboard_bind( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1, nsobject_t arg2, nsobject_t arg3 );

// Signature from Objective-C Runtime: v awakeFromNib @ :
void 				nspasteboard_awakeFromNib( nspasteboard_t object );

// Signature from Objective-C Runtime: @ userInterfaceItemIdentifier @ :
nsobject_t 			nspasteboard_userInterfaceItemIdentifier( nspasteboard_t object );

// Signature from Objective-C Runtime: v setUserInterfaceItemIdentifier: @ : @
void 				nspasteboard_setUserInterfaceItemIdentifier( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v unbind: @ : @
void 				nspasteboard_unbind( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: # valueClassForBinding: @ : @
nsclass_t 			nspasteboard_valueClassForBinding( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ NS_observationForKeyPath:options:block: @ : @ Q @?
nsobject_t 			nspasteboard_NS_observationForKeyPath( nspasteboard_t object, nsobject_t arg0, unsigned long long arg1, nsobject_t* arg2 );

// Signature from Objective-C Runtime: @ NS_observationForKeyPaths:options:block: @ : @ Q @?
nsobject_t 			nspasteboard_NS_observationForKeyPaths( nspasteboard_t object, nsobject_t arg0, unsigned long long arg1, nsobject_t* arg2 );

// Signature from Objective-C Runtime: @ optionDescriptionsForBinding: @ : @
nsobject_t 			nspasteboard_optionDescriptionsForBinding( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ exposedBindings @ :
nsobject_t 			nspasteboard_exposedBindings( nspasteboard_t object );

// Signature from Objective-C Runtime: @ infoForBinding: @ : @
nsobject_t 			nspasteboard_infoForBinding( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v prepareForInterfaceBuilder @ :
void 				nspasteboard_prepareForInterfaceBuilder( nspasteboard_t object );

// Signature from Objective-C Runtime: v accessibilityAddTemporaryChild: @ : @
void 				nspasteboard_accessibilityAddTemporaryChild( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v accessibilityRemoveTemporaryChild: @ : @
void 				nspasteboard_accessibilityRemoveTemporaryChild( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ NSLifeguard_autorelease @ :
nsobject_t 			nspasteboard_NSLifeguard_autorelease( nspasteboard_t object );

// Signature from Objective-C Runtime: v accessibilitySetPresenterProcessIdentifier: @ : i
void 				nspasteboard_accessibilitySetPresenterProcessIdentifier( nspasteboard_t object, int arg0 );

// Signature from Objective-C Runtime: @ NS_tiledLayerVisibleRect @ :
nsobject_t 			nspasteboard_NS_tiledLayerVisibleRect( nspasteboard_t object );

// Signature from Objective-C Runtime: v NS_addTiledLayerDescendent: @ : @
void 				nspasteboard_NS_addTiledLayerDescendent( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v NS_removeTiledLayerDescendent: @ : @
void 				nspasteboard_NS_removeTiledLayerDescendent( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c CAMLTypeSupportedForKey: @ : @
char 				nspasteboard_CAMLTypeSupportedForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ CAMLTypeForKey: @ : @
nsobject_t 			nspasteboard_CAMLTypeForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c CA_validateValue:forKey: @ : @ @
char 				nspasteboard_CA_validateValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v encodeWithCAMLWriter: @ : @
void 				nspasteboard_encodeWithCAMLWriter( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ CA_interpolateValues:::interpolator: @ : @ @ @ r^{ValueInterpolator=dddddddddB}
nsobject_t 			nspasteboard_CA_interpolateValues( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1, nsobject_t arg2, ValueInterpolator* arg3 );

// Signature from Objective-C Runtime: @ CAMLType @ :
nsobject_t 			nspasteboard_CAMLType( nspasteboard_t object );

// Signature from Objective-C Runtime: @ CA_archivingValueForKey: @ : @
nsobject_t 			nspasteboard_CA_archivingValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ CA_roundToIntegerFromValue: @ : @
nsobject_t 			nspasteboard_CA_roundToIntegerFromValue( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ CA_addValue:multipliedBy: @ : @ i
nsobject_t 			nspasteboard_CA_addValue( nspasteboard_t object, nsobject_t arg0, int arg1 );

// Signature from Objective-C Runtime: @ CA_interpolateValue:byFraction: @ : @ f
nsobject_t 			nspasteboard_CA_interpolateValue( nspasteboard_t object, nsobject_t arg0, float arg1 );

// Signature from Objective-C Runtime: d CA_distanceToValue: @ : @
double 				nspasteboard_CA_distanceToValue( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v CA_prepareRenderValue @ :
void 				nspasteboard_CA_prepareRenderValue( nspasteboard_t object );

// Signature from Objective-C Runtime: ^{Object=^^?{Atomic={?=i}}} CA_copyRenderValue @ :
Object* 			nspasteboard_CA_copyRenderValue( nspasteboard_t object );

// Signature from Objective-C Runtime: c supportsRBSXPCSecureCoding @ :
char 				nspasteboard_supportsRBSXPCSecureCoding( nspasteboard_t object );

// Signature from Objective-C Runtime: c RBSIsXPCObject @ :
char 				nspasteboard_RBSIsXPCObject( nspasteboard_t object );

// Signature from Objective-C Runtime: @ NSRepresentation @ :
nsobject_t 			nspasteboard_NSRepresentation( nspasteboard_t object );

// Signature from Objective-C Runtime: c supportsBSXPCSecureCoding @ :
char 				nspasteboard_supportsBSXPCSecureCoding( nspasteboard_t object );

// Signature from Objective-C Runtime: c bs_isPlistableType @ :
char 				nspasteboard_bs_isPlistableType( nspasteboard_t object );

// Signature from Objective-C Runtime: @ bs_secureEncoded @ :
nsobject_t 			nspasteboard_bs_secureEncoded( nspasteboard_t object );

// Signature from Objective-C Runtime: @ bs_encoded @ :
nsobject_t 			nspasteboard_bs_encoded( nspasteboard_t object );

// Signature from Objective-C Runtime: # classForCoder @ :
nsclass_t 			nspasteboard_classForCoder( nspasteboard_t object );

// Signature from Objective-C Runtime: @ replacementObjectForCoder: @ : @
nsobject_t 			nspasteboard_replacementObjectForCoder( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ awakeAfterUsingCoder: @ : @
nsobject_t 			nspasteboard_awakeAfterUsingCoder( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c implementsSelector: @ : :
char 				nspasteboard_implementsSelector( nspasteboard_t object, nsselector_t arg0 );

// Signature from Objective-C Runtime: v setObservationInfo: @ : ^v
void 				nspasteboard_setObservationInfo( nspasteboard_t object, void* arg0 );

// Signature from Objective-C Runtime: v setValue:forKey: @ : @ @
void 				nspasteboard_setValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ replacementObjectForPortCoder: @ : @
nsobject_t 			nspasteboard_replacementObjectForPortCoder( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v willChangeValueForKey: @ : @
void 				nspasteboard_willChangeValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v didChangeValueForKey: @ : @
void 				nspasteboard_didChangeValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ dictionaryWithValuesForKeys: @ : @
nsobject_t 			nspasteboard_dictionaryWithValuesForKeys( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ valueForKey: @ : @
nsobject_t 			nspasteboard_valueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ valueForUndefinedKey: @ : @
nsobject_t 			nspasteboard_valueForUndefinedKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: # classForKeyedArchiver @ :
nsclass_t 			nspasteboard_classForKeyedArchiver( nspasteboard_t object );

// Signature from Objective-C Runtime: @ replacementObjectForKeyedArchiver: @ : @
nsobject_t 			nspasteboard_replacementObjectForKeyedArchiver( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ valueForKeyPath: @ : @
nsobject_t 			nspasteboard_valueForKeyPath( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ addObserver: @ : @
nsobject_t 			nspasteboard_addObserver( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ objectSpecifier @ :
nsobject_t 			nspasteboard_objectSpecifier( nspasteboard_t object );

// Signature from Objective-C Runtime: @ replacementObjectForArchiver: @ : @
nsobject_t 			nspasteboard_replacementObjectForArchiver( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: # classForArchiver @ :
nsclass_t 			nspasteboard_classForArchiver( nspasteboard_t object );

// Signature from Objective-C Runtime: @ attributeKeys @ :
nsobject_t 			nspasteboard_attributeKeys( nspasteboard_t object );

// Signature from Objective-C Runtime: @ toOneRelationshipKeys @ :
nsobject_t 			nspasteboard_toOneRelationshipKeys( nspasteboard_t object );

// Signature from Objective-C Runtime: @ toManyRelationshipKeys @ :
nsobject_t 			nspasteboard_toManyRelationshipKeys( nspasteboard_t object );

// Signature from Objective-C Runtime: @ inverseForRelationshipKey: @ : @
nsobject_t 			nspasteboard_inverseForRelationshipKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ classDescription @ :
nsobject_t 			nspasteboard_classDescription( nspasteboard_t object );

// Signature from Objective-C Runtime: @ copyScriptingValue:forKey:withProperties: @ : @ @ @
nsobject_t 			nspasteboard_copyScriptingValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: ^{objc_method_description=:*} methodDescriptionForSelector: @ : :
objc_method_description* nspasteboard_methodDescriptionForSelector( nspasteboard_t object, nsselector_t arg0 );

// Signature from Objective-C Runtime: @ newScriptingObjectOfClass:forValueForKey:withContentsValue:properties: @ : # @ @ @
nsobject_t 			nspasteboard_newScriptingObjectOfClass( nspasteboard_t object, nsclass_t arg0, nsobject_t arg1, nsobject_t arg2, nsobject_t arg3 );

// Signature from Objective-C Runtime: @ handleQueryWithUnboundKey: @ : @
nsobject_t 			nspasteboard_handleQueryWithUnboundKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v handleTakeValue:forUnboundKey: @ : @ @
void 				nspasteboard_handleTakeValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ storedValueForKey: @ : @
nsobject_t 			nspasteboard_storedValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v takeStoredValue:forKey: @ : @ @
void 				nspasteboard_takeStoredValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v takeValue:forKey: @ : @ @
void 				nspasteboard_takeValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ valuesForKeys: @ : @
nsobject_t 			nspasteboard_valuesForKeys( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v takeValuesFromDictionary: @ : @
void 				nspasteboard_takeValuesFromDictionary( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v unableToSetNilForKey: @ : @
void 				nspasteboard_unableToSetNilForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ keyValueBindingForKey:typeMask: @ : @ Q
nsobject_t 			nspasteboard_keyValueBindingForKey( nspasteboard_t object, nsobject_t arg0, unsigned long long arg1 );

// Signature from Objective-C Runtime: @ createKeyValueBindingForKey:typeMask: @ : @ Q
nsobject_t 			nspasteboard_createKeyValueBindingForKey( nspasteboard_t object, nsobject_t arg0, unsigned long long arg1 );

// Signature from Objective-C Runtime: @ mutableArrayValueForKeyPath: @ : @
nsobject_t 			nspasteboard_mutableArrayValueForKeyPath( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ mutableOrderedSetValueForKeyPath: @ : @
nsobject_t 			nspasteboard_mutableOrderedSetValueForKeyPath( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ mutableSetValueForKeyPath: @ : @
nsobject_t 			nspasteboard_mutableSetValueForKeyPath( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v removeObservation: @ : @
void 				nspasteboard_removeObservation( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v receiveObservedValue: @ : @
void 				nspasteboard_receiveObservedValue( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v receiveObservedError: @ : @
void 				nspasteboard_receiveObservedError( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v finishObserving @ :
void 				nspasteboard_finishObserving( nspasteboard_t object );

// Signature from Objective-C Runtime: v setObservation:forObservingKeyPath: @ : @ @
void 				nspasteboard_setObservation( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v observeValueForKeyPath:ofObject:change:context: @ : @ @ @ ^v
void 				nspasteboard_observeValueForKeyPath( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1, nsobject_t arg2, void* arg3 );

// Signature from Objective-C Runtime: v removeObserver:forKeyPath:context: @ : @ @ ^v
void 				nspasteboard_removeObserver( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1, void* arg2 );

// Signature from Objective-C Runtime: @ className @ :
nsobject_t 			nspasteboard_className( nspasteboard_t object );

// Signature from Objective-C Runtime: @ addChainedObservers: @ : @
nsobject_t 			nspasteboard_addChainedObservers( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ addObserverBlock: @ : @?
nsobject_t 			nspasteboard_addObserverBlock( nspasteboard_t object, nsobject_t* arg0 );

// Signature from Objective-C Runtime: @ addObservationTransformer: @ : @?
nsobject_t 			nspasteboard_addObservationTransformer( nspasteboard_t object, nsobject_t* arg0 );

// Signature from Objective-C Runtime: v setNilValueForKey: @ : @
void 				nspasteboard_setNilValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ mutableArrayValueForKey: @ : @
nsobject_t 			nspasteboard_mutableArrayValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ mutableOrderedSetValueForKey: @ : @
nsobject_t 			nspasteboard_mutableOrderedSetValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ mutableSetValueForKey: @ : @
nsobject_t 			nspasteboard_mutableSetValueForKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v setValuesForKeysWithDictionary: @ : @
void 				nspasteboard_setValuesForKeysWithDictionary( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v willChange:valuesAtIndexes:forKey: @ : Q @ @
void 				nspasteboard_willChange( nspasteboard_t object, unsigned long long arg0, nsobject_t arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: v didChange:valuesAtIndexes:forKey: @ : Q @ @
void 				nspasteboard_didChange( nspasteboard_t object, unsigned long long arg0, nsobject_t arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: ^v observationInfo @ :
void* 				nspasteboard_observationInfo( nspasteboard_t object );

// Signature from Objective-C Runtime: @ autoContentAccessingProxy @ :
nsobject_t 			nspasteboard_autoContentAccessingProxy( nspasteboard_t object );

// Signature from Objective-C Runtime: @ coerceValue:forKey: @ : @ @
nsobject_t 			nspasteboard_coerceValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v setScriptingProperties: @ : @
void 				nspasteboard_setScriptingProperties( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ scriptingValueForSpecifier: @ : @
nsobject_t 			nspasteboard_scriptingValueForSpecifier( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ scriptingProperties @ :
nsobject_t 			nspasteboard_scriptingProperties( nspasteboard_t object );

// Signature from Objective-C Runtime: @ coerceValueForScriptingProperties: @ : @
nsobject_t 			nspasteboard_coerceValueForScriptingProperties( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ valueAtIndex:inPropertyWithKey: @ : Q @
nsobject_t 			nspasteboard_valueAtIndex( nspasteboard_t object, unsigned long long arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ valueWithName:inPropertyWithKey: @ : @ @
nsobject_t 			nspasteboard_valueWithName( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ valueWithUniqueID:inPropertyWithKey: @ : @ @
nsobject_t 			nspasteboard_valueWithUniqueID( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v insertValue:atIndex:inPropertyWithKey: @ : @ Q @
void 				nspasteboard_insertValue( nspasteboard_t object, nsobject_t arg0, unsigned long long arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: v replaceValueAtIndex:inPropertyWithKey:withValue: @ : Q @ @
void 				nspasteboard_replaceValueAtIndex( nspasteboard_t object, unsigned long long arg0, nsobject_t arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: v removeValueAtIndex:fromPropertyWithKey: @ : Q @
void 				nspasteboard_removeValueAtIndex( nspasteboard_t object, unsigned long long arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: # classForPortCoder @ :
nsclass_t 			nspasteboard_classForPortCoder( nspasteboard_t object );

// Signature from Objective-C Runtime: v performSelector:withObject:afterDelay:inModes: @ : : @ d @
void 				nspasteboard_performSelector( nspasteboard_t object, nsselector_t arg0, nsobject_t arg1, double arg2, nsobject_t arg3 );

// Signature from Objective-C Runtime: I classCode @ :
unsigned int 		nspasteboard_classCode( nspasteboard_t object );

// Signature from Objective-C Runtime: c isEqualTo: @ : @
char 				nspasteboard_isEqualTo( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isLessThanOrEqualTo: @ : @
char 				nspasteboard_isLessThanOrEqualTo( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isLessThan: @ : @
char 				nspasteboard_isLessThan( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isGreaterThanOrEqualTo: @ : @
char 				nspasteboard_isGreaterThanOrEqualTo( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isGreaterThan: @ : @
char 				nspasteboard_isGreaterThan( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isNotEqualTo: @ : @
char 				nspasteboard_isNotEqualTo( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c doesContain: @ : @
char 				nspasteboard_doesContain( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isLike: @ : @
char 				nspasteboard_isLike( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isCaseInsensitiveLike: @ : @
char 				nspasteboard_isCaseInsensitiveLike( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v performSelectorOnMainThread:withObject:waitUntilDone:modes: @ : : @ c @
void 				nspasteboard_performSelectorOnMainThread( nspasteboard_t object, nsselector_t arg0, nsobject_t arg1, char arg2, nsobject_t arg3 );

// Signature from Objective-C Runtime: v performSelectorInBackground:withObject: @ : : @
void 				nspasteboard_performSelectorInBackground( nspasteboard_t object, nsselector_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ classDescriptionForDestinationKey: @ : @
nsobject_t 			nspasteboard_classDescriptionForDestinationKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ entityName @ :
nsobject_t 			nspasteboard_entityName( nspasteboard_t object );

// Signature from Objective-C Runtime: c ownsDestinationObjectsForRelationshipKey: @ : @
char 				nspasteboard_ownsDestinationObjectsForRelationshipKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isToManyKey: @ : @
char 				nspasteboard_isToManyKey( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: v removeObject:fromPropertyWithKey: @ : @ @
void 				nspasteboard_removeObject( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v addObject:toPropertyWithKey: @ : @ @
void 				nspasteboard_addObject( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ validateTakeValue:forKeyPath: @ : @ @
nsobject_t 			nspasteboard_validateTakeValue( nspasteboard_t object, nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ allPropertyKeys @ :
nsobject_t 			nspasteboard_allPropertyKeys( nspasteboard_t object );

// Signature from Objective-C Runtime: v clearProperties @ :
void 				nspasteboard_clearProperties( nspasteboard_t object );

// Signature from Objective-C Runtime: v flushKeyBindings @ :
void 				nspasteboard_flushKeyBindings( nspasteboard_t object );

// Signature from Objective-C Runtime: v takeStoredValuesFromDictionary: @ : @
void 				nspasteboard_takeStoredValuesFromDictionary( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c isNSDate__ @ :
char 				nspasteboard_isNSDate__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSString__ @ :
char 				nspasteboard_isNSString__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSCFConstantString__ @ :
char 				nspasteboard_isNSCFConstantString__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSNumber__ @ :
char 				nspasteboard_isNSNumber__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSArray__ @ :
char 				nspasteboard_isNSArray__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSDictionary__ @ :
char 				nspasteboard_isNSDictionary__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSSet__ @ :
char 				nspasteboard_isNSSet__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSData__ @ :
char 				nspasteboard_isNSData__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSObject__ @ :
char 				nspasteboard_isNSObject__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSOrderedSet__ @ :
char 				nspasteboard_isNSOrderedSet__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSTimeZone__ @ :
char 				nspasteboard_isNSTimeZone__( nspasteboard_t object );

// Signature from Objective-C Runtime: c isNSValue__ @ :
char 				nspasteboard_isNSValue__( nspasteboard_t object );

// Signature from Objective-C Runtime: @ description @ :
nsobject_t 			nspasteboard_description( nspasteboard_t object );

// Signature from Objective-C Runtime: v doesNotRecognizeSelector: @ : :
void 				nspasteboard_doesNotRecognizeSelector( nspasteboard_t object, nsselector_t arg0 );

// Signature from Objective-C Runtime: @ methodSignatureForSelector: @ : :
nsobject_t 			nspasteboard_methodSignatureForSelector( nspasteboard_t object, nsselector_t arg0 );

// Signature from Objective-C Runtime: @ retain @ :
nsobject_t 			nspasteboard_retain( nspasteboard_t object );

// Signature from Objective-C Runtime: Q retainCount @ :
unsigned long long 	nspasteboard_retainCount( nspasteboard_t object );

// Signature from Objective-C Runtime: @ autorelease @ :
nsobject_t 			nspasteboard_autorelease( nspasteboard_t object );

// Signature from Objective-C Runtime: @ copy @ :
nsobject_t 			nspasteboard_copy( nspasteboard_t object );

// Signature from Objective-C Runtime: v finalize @ :
void 				nspasteboard_finalize( nspasteboard_t object );

// Signature from Objective-C Runtime: c isEqual: @ : @
char 				nspasteboard_isEqual( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: # class @ :
nsclass_t 			nspasteboard_class( nspasteboard_t object );

// Signature from Objective-C Runtime: @ self @ :
nsobject_t 			nspasteboard_self( nspasteboard_t object );

// Signature from Objective-C Runtime: c isProxy @ :
char 				nspasteboard_isProxy( nspasteboard_t object );

// Signature from Objective-C Runtime: c isKindOfClass: @ : #
char 				nspasteboard_isKindOfClass( nspasteboard_t object, nsclass_t arg0 );

// Signature from Objective-C Runtime: c isMemberOfClass: @ : #
char 				nspasteboard_isMemberOfClass( nspasteboard_t object, nsclass_t arg0 );

// Signature from Objective-C Runtime: c conformsToProtocol: @ : @
char 				nspasteboard_conformsToProtocol( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: c respondsToSelector: @ : :
char 				nspasteboard_respondsToSelector( nspasteboard_t object, nsselector_t arg0 );

// Signature from Objective-C Runtime: ^{_NSZone=} zone @ :
_NSZone* 			nspasteboard_zone( nspasteboard_t object );

// Signature from Objective-C Runtime: Q hash @ :
unsigned long long 	nspasteboard_hash( nspasteboard_t object );

// Signature from Objective-C Runtime: # superclass @ :
nsclass_t 			nspasteboard_superclass( nspasteboard_t object );

// Signature from Objective-C Runtime: @ debugDescription @ :
nsobject_t 			nspasteboard_debugDescription( nspasteboard_t object );

// Signature from Objective-C Runtime: @ init @ :
nsobject_t 			nspasteboard_init( nspasteboard_t object );

// Signature from Objective-C Runtime: c retainWeakReference @ :
char 				nspasteboard_retainWeakReference( nspasteboard_t object );

// Signature from Objective-C Runtime: c allowsWeakReference @ :
char 				nspasteboard_allowsWeakReference( nspasteboard_t object );

// Signature from Objective-C Runtime: c isFault @ :
char 				nspasteboard_isFault( nspasteboard_t object );

// Signature from Objective-C Runtime: v forwardInvocation: @ : @
void 				nspasteboard_forwardInvocation( nspasteboard_t object, nsobject_t arg0 );

// Signature from Objective-C Runtime: @ forwardingTargetForSelector: @ : :
nsobject_t 			nspasteboard_forwardingTargetForSelector( nspasteboard_t object, nsselector_t arg0 );

// Signature from Objective-C Runtime: @ mutableCopy @ :
nsobject_t 			nspasteboard_mutableCopy( nspasteboard_t object );

// Signature from Objective-C Runtime: @ allocWithZone: @ : ^{_NSZone=}
nsobject_t 			nspasteboard_allocWithZone( _NSZone* arg0 );

// Signature from Objective-C Runtime: v initialize @ :
void 				nspasteboard_initialize( );

// Signature from Objective-C Runtime: @ alloc @ :
nspasteboard_t 		nspasteboard_alloc( );

// Signature from Objective-C Runtime: @ generalPasteboard @ :
nsobject_t 			nspasteboard_generalPasteboard( );

// Signature from Objective-C Runtime: @ pasteboardWithName: @ : @
nsobject_t 			nspasteboard_pasteboardWithName( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ typesFilterableTo: @ : @
nsobject_t 			nspasteboard_typesFilterableTo( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ pasteboardByFilteringData:ofType: @ : @ @
nsobject_t 			nspasteboard_pasteboardByFilteringData( nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: @ pasteboardByFilteringFile: @ : @
nsobject_t 			nspasteboard_pasteboardByFilteringFile( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ pasteboardByFilteringTypesInPasteboard: @ : @
nsobject_t 			nspasteboard_pasteboardByFilteringTypesInPasteboard( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ testingPasteboardWithCFPasteboard: @ : ^v
nsobject_t 			nspasteboard_testingPasteboardWithCFPasteboard( void* arg0 );

// Signature from Objective-C Runtime: @ pasteboardWithUniqueName @ :
nsobject_t 			nspasteboard_pasteboardWithUniqueName( );

// Signature from Objective-C Runtime: @ defaultPlaceholderForMarker:withBinding: @ : @ @
nsobject_t 			nspasteboard_defaultPlaceholderForMarker( nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v exposeBinding: @ : @
void 				nspasteboard_exposeBinding( nsobject_t arg0 );

// Signature from Objective-C Runtime: v setDefaultPlaceholder:forMarker:withBinding: @ : @ @ @
void 				nspasteboard_setDefaultPlaceholder( nsobject_t arg0, nsobject_t arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: c CA_automaticallyNotifiesObservers: @ : #
char 				nspasteboard_CA_automaticallyNotifiesObservers( nsclass_t arg0 );

// Signature from Objective-C Runtime: c CA_encodesPropertyConditionally:type: @ : I i
char 				nspasteboard_CA_encodesPropertyConditionally( unsigned int arg0, int arg1 );

// Signature from Objective-C Runtime: @ CA_CAMLPropertyForKey: @ : @
nsobject_t 			nspasteboard_CA_CAMLPropertyForKey( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ bs_secureDecodedFromData: @ : @
nsobject_t 			nspasteboard_bs_secureDecodedFromData( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ bs_secureDataFromObject: @ : @
nsobject_t 			nspasteboard_bs_secureDataFromObject( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ bs_secureObjectFromData:ofClass: @ : @ #
nsobject_t 			nspasteboard_bs_secureObjectFromData( nsobject_t arg0, nsclass_t arg1 );

// Signature from Objective-C Runtime: @ bs_dataFromObject: @ : @
nsobject_t 			nspasteboard_bs_dataFromObject( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ bs_objectFromData: @ : @
nsobject_t 			nspasteboard_bs_objectFromData( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ bs_decodedFromData: @ : @
nsobject_t 			nspasteboard_bs_decodedFromData( nsobject_t arg0 );

// Signature from Objective-C Runtime: v load @ :
void 				nspasteboard_load( );

// Signature from Objective-C Runtime: q version @ :
long long 			nspasteboard_version( );

// Signature from Objective-C Runtime: c instancesImplementSelector: @ : :
char 				nspasteboard_instancesImplementSelector( nsselector_t arg0 );

// Signature from Objective-C Runtime: v poseAsClass: @ : #
void 				nspasteboard_poseAsClass( nsclass_t arg0 );

// Signature from Objective-C Runtime: v setVersion: @ : q
void 				nspasteboard_setVersion( long long arg0 );

// Signature from Objective-C Runtime: c automaticallyNotifiesObserversForKey: @ : @
char 				nspasteboard_automaticallyNotifiesObserversForKey( nsobject_t arg0 );

// Signature from Objective-C Runtime: @ classFallbacksForKeyedArchiver @ :
nsobject_t 			nspasteboard_classFallbacksForKeyedArchiver( );

// Signature from Objective-C Runtime: # classForKeyedUnarchiver @ :
nsclass_t 			nspasteboard_classForKeyedUnarchiver( );

// Signature from Objective-C Runtime: c useStoredAccessor @ :
char 				nspasteboard_useStoredAccessor( );

// Signature from Objective-C Runtime: c accessInstanceVariablesDirectly @ :
char 				nspasteboard_accessInstanceVariablesDirectly( );

// Signature from Objective-C Runtime: ^{objc_method_description=:*} instanceMethodDescriptionForSelector: @ : :
objc_method_description* nspasteboard_instanceMethodDescriptionForSelector( nsselector_t arg0 );

// Signature from Objective-C Runtime: @ keyPathsForValuesAffectingValueForKey: @ : @
nsobject_t 			nspasteboard_keyPathsForValuesAffectingValueForKey( nsobject_t arg0 );

// Signature from Objective-C Runtime: v setKeys:triggerChangeNotificationsForDependentKey: @ : @ @
void 				nspasteboard_setKeys( nsobject_t arg0, nsobject_t arg1 );

// Signature from Objective-C Runtime: v cancelPreviousPerformRequestsWithTarget:selector:object: @ : @ : @
void 				nspasteboard_cancelPreviousPerformRequestsWithTarget( nsobject_t arg0, nsselector_t arg1, nsobject_t arg2 );

// Signature from Objective-C Runtime: v flushAllKeyBindings @ :
void 				nspasteboard_flushAllKeyBindings( );

// Signature from Objective-C Runtime: v flushClassKeyBindings @ :
void 				nspasteboard_flushClassKeyBindings( );

// Signature from Objective-C Runtime: @ SFSQLiteClassName @ :
nsobject_t 			nspasteboard_SFSQLiteClassName( );

// Signature from Objective-C Runtime: @ instanceMethodSignatureForSelector: @ : :
nsobject_t 			nspasteboard_instanceMethodSignatureForSelector( nsselector_t arg0 );

// Signature from Objective-C Runtime: @ copyWithZone: @ : ^{_NSZone=}
nsobject_t 			nspasteboard_copyWithZone( _NSZone* arg0 );

// Signature from Objective-C Runtime: @ new @ :
nsobject_t 			nspasteboard_new( );

// Signature from Objective-C Runtime: c resolveInstanceMethod: @ : :
char 				nspasteboard_resolveInstanceMethod( nsselector_t arg0 );

// Signature from Objective-C Runtime: c resolveClassMethod: @ : :
char 				nspasteboard_resolveClassMethod( nsselector_t arg0 );

// Signature from Objective-C Runtime: @ mutableCopyWithZone: @ : ^{_NSZone=}
nsobject_t 			nspasteboard_mutableCopyWithZone( _NSZone* arg0 );

// Signature from Objective-C Runtime: c isSubclassOfClass: @ : #
char 				nspasteboard_isSubclassOfClass( nsclass_t arg0 );

// Signature from Objective-C Runtime: c isAncestorOfObject: @ : @
char 				nspasteboard_isAncestorOfObject( nsobject_t arg0 );

// Signature from Objective-C Runtime: c instancesRespondToSelector: @ : :
char 				nspasteboard_instancesRespondToSelector( nsselector_t arg0 );

#endif